### ISSUE TITLE
Add DetectionFinding example from Prowler

### ISSUE THREAD

**Issue by jfagoagas** [ocsf/examples#75]
Hello,

I'm one of the https://github.com/prowler-cloud/prowler maintainers and we want to add an example of the DetectionFinding we use to report findings. How could we do that? It is not clear to us where should we put an example file.

Thanks in advance.
Best.

**Comment by floydtree** [comment]
Hey, if you are looking to submit mappings of Prowler's Detection Finding to OCSF's event class, this should get you going - https://github.com/ocsf/examples?tab=readme-ov-file#how-to-submit-your-mappings

Let me know if you have questions, happy to chat.

**Comment by jfagoagas** [comment]
Hello @floydtree, thank you for your guidance. At first it was not clear to me where to place it but I think I made it the right way in the above PR. Please let me know once you review it.

Thanks!
