### ISSUE TITLE
Set directory structure to "Category -> Class -> Activity"

### ISSUE THREAD

**Issue by mikeradka** [ocsf/examples#8]
The current directory structure is "Category -> Class". To better organize examples by their activity, let's add 'activity' subfolders to each class.

**Comment by pagbabian-splunk** [comment]
I think as the examples get more and more populated, this may be easier to navigate for people, even though to start with it will be more clicks and sparse.  Good idea, do we need to start with that now or can we move to that once we have more examples that warrant it?
